// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2RxzP-oP-yyPcEmkz03cOy_JIkzG3rQ',
    appId: '1:720433620908:web:444bd2e0a3b80461f63c09',
    messagingSenderId: '720433620908',
    projectId: 'study-app-flutter-4caa4',
    authDomain: 'study-app-flutter-4caa4.firebaseapp.com',
    storageBucket: 'study-app-flutter-4caa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzm0pDuIaLLSPYhM8Hik4DUcnyDAaveEU',
    appId: '1:720433620908:android:cc9ff4ccb737cc65f63c09',
    messagingSenderId: '720433620908',
    projectId: 'study-app-flutter-4caa4',
    storageBucket: 'study-app-flutter-4caa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOAr0xMpgmOAZn4QyTpIPAIpmWqIHkPE',
    appId: '1:720433620908:ios:c74bcf63484c98eaf63c09',
    messagingSenderId: '720433620908',
    projectId: 'study-app-flutter-4caa4',
    storageBucket: 'study-app-flutter-4caa4.appspot.com',
    iosClientId: '720433620908-vnag90qt6ol5hqggv5316j5jj0dqopub.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYOAr0xMpgmOAZn4QyTpIPAIpmWqIHkPE',
    appId: '1:720433620908:ios:c74bcf63484c98eaf63c09',
    messagingSenderId: '720433620908',
    projectId: 'study-app-flutter-4caa4',
    storageBucket: 'study-app-flutter-4caa4.appspot.com',
    iosClientId: '720433620908-vnag90qt6ol5hqggv5316j5jj0dqopub.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
